<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InvoiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('invoices')->delete();
        
        DB::table('invoices')->insert([
            [
                'id' => 1,
                'client_id' => 2,
                'invoice_number' => 'INV/2026/01/001',
                'invoice_date' => '2026-01-01',
                'due_date' => '2026-01-15',
                'customer_name' => 'PT. Maju Jaya',
                'customer_address' => 'Jl. Sudirman No. 123, Jakarta Pusat',
                'customer_phone' => '021-1234567',
                'customer_email' => 'info@majujaya.com',
                'payment_terms' => '14 hari',
                'notes' => 'Terima kasih atas kepercayaan Anda',
                'subtotal' => '29500000.00',
                'discount_percentage' => '5.00',
                'discount_amount' => '1475000.00',
                'tax_percentage' => '11.00',
                'tax_amount' => '3082750.00',
                'other_charges' => '50000.00',
                'total_amount' => '31157750.00',
                'status' => 'paid',
                'prepared_by' => 'John Doe',
                'approved_by' => 'Jane Smith',
                'created_at' => '2026-02-12 07:15:10',
                'updated_at' => '2026-02-13 03:35:25',
                'deleted_at' => NULL,
            ],
            [
                'id' => 2,
                'client_id' => 3,
                'invoice_number' => 'INV/2026/01/002',
                'invoice_date' => '2026-01-02',
                'due_date' => '2026-01-16',
                'customer_name' => 'CV. Berkah Sentosa',
                'customer_address' => 'Jl. Gatot Subroto No. 45, Bandung',
                'customer_phone' => '022-7654321',
                'customer_email' => 'berkah@sentosa.com',
                'payment_terms' => '14 hari',
                'notes' => NULL,
                'subtotal' => '25500000.00',
                'discount_percentage' => '10.00',
                'discount_amount' => '2550000.00',
                'tax_percentage' => '11.00',
                'tax_amount' => '2524500.00',
                'other_charges' => '0.00',
                'total_amount' => '25474500.00',
                'status' => 'pending',
                'prepared_by' => 'Alice Johnson',
                'approved_by' => 'Bob Wilson',
                'created_at' => '2026-02-12 07:15:11',
                'updated_at' => '2026-02-13 03:35:25',
                'deleted_at' => NULL,
            ],
            [
                'id' => 3,
                'client_id' => 4,
                'invoice_number' => 'INV/2026/01/003',
                'invoice_date' => '2026-01-03',
                'due_date' => NULL,
                'customer_name' => 'Toko ABC',
                'customer_address' => 'Jl. Ahmad Yani No. 78, Surabaya',
                'customer_phone' => '031-9876543',
                'customer_email' => NULL,
                'payment_terms' => '30 hari',
                'notes' => NULL,
                'subtotal' => '25400000.00',
                'discount_percentage' => '0.00',
                'discount_amount' => '0.00',
                'tax_percentage' => '11.00',
                'tax_amount' => '2794000.00',
                'other_charges' => '0.00',
                'total_amount' => '28194000.00',
                'status' => 'paid',
                'prepared_by' => 'Charlie Brown',
                'approved_by' => NULL,
                'created_at' => '2026-02-12 07:15:11',
                'updated_at' => '2026-02-13 03:35:25',
                'deleted_at' => NULL,
            ],
            [
                'id' => 4,
                'client_id' => NULL,
                'invoice_number' => 'INV/2026/01/004',
                'invoice_date' => '2026-01-04',
                'due_date' => NULL,
                'customer_name' => 'Restoran XYZ',
                'customer_address' => 'Jl. Thamrin No. 99, Jakarta',
                'customer_phone' => NULL,
                'customer_email' => NULL,
                'payment_terms' => '7 hari',
                'notes' => NULL,
                'subtotal' => '12000000.00',
                'discount_percentage' => '0.00',
                'discount_amount' => '0.00',
                'tax_percentage' => '11.00',
                'tax_amount' => '1320000.00',
                'other_charges' => '0.00',
                'total_amount' => '13320000.00',
                'status' => 'cancelled',
                'prepared_by' => NULL,
                'approved_by' => NULL,
                'created_at' => '2026-02-12 07:15:11',
                'updated_at' => '2026-02-13 03:35:25',
                'deleted_at' => '2026-02-12 07:33:12',
            ],
            [
                'id' => 5,
                'client_id' => 1,
                'invoice_number' => 'INV/2026/01/005',
                'invoice_date' => '2026-01-05',
                'due_date' => NULL,
                'customer_name' => 'Rachmad Hartono',
                'customer_address' => NULL,
                'customer_phone' => NULL,
                'customer_email' => 'rahmadhartono62@gmail.com',
                'payment_terms' => NULL,
                'notes' => NULL,
                'subtotal' => '3900000.00',
                'discount_percentage' => '0.00',
                'discount_amount' => '0.00',
                'tax_percentage' => '0.00',
                'tax_amount' => '0.00',
                'other_charges' => '0.00',
                'total_amount' => '3900000.00',
                'status' => 'pending',
                'prepared_by' => NULL,
                'approved_by' => NULL,
                'created_at' => '2026-02-12 08:19:19',
                'updated_at' => '2026-02-13 03:35:25',
                'deleted_at' => NULL,
            ],
            [
                'id' => 6,
                'client_id' => 5,
                'invoice_number' => 'INV/2026/01/006',
                'invoice_date' => '2026-01-06',
                'due_date' => NULL,
                'customer_name' => 'Agus',
                'customer_address' => NULL,
                'customer_phone' => NULL,
                'customer_email' => NULL,
                'payment_terms' => NULL,
                'notes' => NULL,
                'subtotal' => '4380000.00',
                'discount_percentage' => '0.00',
                'discount_amount' => '0.00',
                'tax_percentage' => '0.00',
                'tax_amount' => '0.00',
                'other_charges' => '0.00',
                'total_amount' => '4380000.00',
                'status' => 'paid',
                'prepared_by' => NULL,
                'approved_by' => NULL,
                'created_at' => '2026-02-12 14:48:41',
                'updated_at' => '2026-02-13 03:35:25',
                'deleted_at' => NULL,
            ],
            [
                'id' => 7,
                'client_id' => 1,
                'invoice_number' => 'INV/2026/01/007',
                'invoice_date' => '2026-01-07',
                'due_date' => NULL,
                'customer_name' => 'Rachmad Hartono',
                'customer_address' => 'JL. Kaswari No 83, Mancasan Lor, Condongcatur, Depok, Sleman',
                'customer_phone' => '082282825606',
                'customer_email' => 'rahmadhartono62@gmail.com',
                'payment_terms' => NULL,
                'notes' => NULL,
                'subtotal' => '4500000.00',
                'discount_percentage' => '0.00',
                'discount_amount' => '0.00',
                'tax_percentage' => '0.00',
                'tax_amount' => '0.00',
                'other_charges' => '0.00',
                'total_amount' => '4500000.00',
                'status' => 'pending',
                'prepared_by' => NULL,
                'approved_by' => NULL,
                'created_at' => '2026-02-12 15:09:48',
                'updated_at' => '2026-02-13 03:35:25',
                'deleted_at' => NULL,
            ],
            [
                'id' => 8,
                'client_id' => 1,
                'invoice_number' => 'INV/2026/01/008',
                'invoice_date' => '2026-01-08',
                'due_date' => NULL,
                'customer_name' => 'Rachmad Hartono',
                'customer_address' => 'JL. Kaswari No 83, Mancasan Lor, Condongcatur, Depok, Sleman, Yogyakarta',
                'customer_phone' => '082282825606',
                'customer_email' => 'rahmadhartono62@gmail.com',
                'payment_terms' => NULL,
                'notes' => NULL,
                'subtotal' => '3200000.00',
                'discount_percentage' => '0.00',
                'discount_amount' => '0.00',
                'tax_percentage' => '0.00',
                'tax_amount' => '0.00',
                'other_charges' => '0.00',
                'total_amount' => '3200000.00',
                'status' => 'pending',
                'prepared_by' => NULL,
                'approved_by' => NULL,
                'created_at' => '2026-02-12 15:22:16',
                'updated_at' => '2026-02-13 03:35:25',
                'deleted_at' => NULL,
            ],
        ]);
    }
}
