<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InvoiceItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('invoice_items')->delete();
        
        DB::table('invoice_items')->insert([
            [
                'id' => 1,
                'invoice_id' => 1,
                'item_code' => 'PD004',
                'item_name' => 'Rak Stainless 4 Tier Non Solid',
                'description' => 'Rak penyimpanan stainless steel 4 tingkat',
                'quantity' => '10.00',
                'unit' => 'Unit',
                'unit_price' => '1700000.00',
                'discount_percentage' => '0.00',
                'discount_amount' => '0.00',
                'subtotal' => '17000000.00',
                'sort_order' => 1,
                'created_at' => '2026-02-12 07:15:11',
                'updated_at' => '2026-02-12 07:15:11',
            ],
            [
                'id' => 2,
                'invoice_id' => 1,
                'item_code' => 'PD005',
                'item_name' => 'Meja Kerja Stainless',
                'description' => 'Meja kerja stainless steel 150x60cm',
                'quantity' => '5.00',
                'unit' => 'Unit',
                'unit_price' => '2500000.00',
                'discount_percentage' => '0.00',
                'discount_amount' => '0.00',
                'subtotal' => '12500000.00',
                'sort_order' => 2,
                'created_at' => '2026-02-12 07:15:11',
                'updated_at' => '2026-02-12 07:15:11',
            ],
            [
                'id' => 3,
                'invoice_id' => 2,
                'item_code' => 'PD001',
                'item_name' => 'Lemari Pendingin 2 Pintu',
                'description' => 'Lemari pendingin kapasitas 500L',
                'quantity' => '3.00',
                'unit' => 'Unit',
                'unit_price' => '8500000.00',
                'discount_percentage' => '0.00',
                'discount_amount' => '0.00',
                'subtotal' => '25500000.00',
                'sort_order' => 1,
                'created_at' => '2026-02-12 07:15:11',
                'updated_at' => '2026-02-12 07:15:11',
            ],
            [
                'id' => 6,
                'invoice_id' => 4,
                'item_code' => 'PD006',
                'item_name' => 'Oven Listrik',
                'description' => NULL,
                'quantity' => '1.00',
                'unit' => 'Unit',
                'unit_price' => '12000000.00',
                'discount_percentage' => '0.00',
                'discount_amount' => '0.00',
                'subtotal' => '12000000.00',
                'sort_order' => 1,
                'created_at' => '2026-02-12 07:15:11',
                'updated_at' => '2026-02-12 07:15:11',
            ],
            [
                'id' => 7,
                'invoice_id' => 5,
                'item_code' => 'ORD-6A20D6',
                'item_name' => 'Grease Trap',
                'description' => NULL,
                'quantity' => '3.00',
                'unit' => 'unit',
                'unit_price' => '1300000.00',
                'discount_percentage' => '0.00',
                'discount_amount' => '0.00',
                'subtotal' => '3900000.00',
                'sort_order' => 0,
                'created_at' => '2026-02-12 08:19:19',
                'updated_at' => '2026-02-12 08:19:19',
            ],
            [
                'id' => 9,
                'invoice_id' => 6,
                'item_code' => 'ORD-A473B5',
                'item_name' => 'Long Sink Knockdown',
                'description' => NULL,
                'quantity' => '1.00',
                'unit' => 'unit',
                'unit_price' => '4000000.00',
                'discount_percentage' => '0.00',
                'discount_amount' => '0.00',
                'subtotal' => '4000000.00',
                'sort_order' => 0,
                'created_at' => '2026-02-12 15:05:00',
                'updated_at' => '2026-02-12 15:05:00',
            ],
            [
                'id' => 10,
                'invoice_id' => 6,
                'item_code' => 'ORD-9AA96E',
                'item_name' => 'Palet Plastik',
                'description' => NULL,
                'quantity' => '1.00',
                'unit' => 'unit',
                'unit_price' => '380000.00',
                'discount_percentage' => '0.00',
                'discount_amount' => '0.00',
                'subtotal' => '380000.00',
                'sort_order' => 0,
                'created_at' => '2026-02-12 15:05:00',
                'updated_at' => '2026-02-12 15:05:00',
            ],
            [
                'id' => 11,
                'invoice_id' => 3,
                'item_code' => 'ORD-C3BC95',
                'item_name' => 'Kompor Gas Industrial',
                'description' => NULL,
                'quantity' => '2.00',
                'unit' => 'unit',
                'unit_price' => '4200000.00',
                'discount_percentage' => '0.00',
                'discount_amount' => '0.00',
                'subtotal' => '8400000.00',
                'sort_order' => 0,
                'created_at' => '2026-02-12 15:08:24',
                'updated_at' => '2026-02-12 15:08:24',
            ],
            [
                'id' => 12,
                'invoice_id' => 3,
                'item_code' => 'ORD-161BAC',
                'item_name' => 'Deep Fryer Listrik',
                'description' => NULL,
                'quantity' => '4.00',
                'unit' => 'unit',
                'unit_price' => '3500000.00',
                'discount_percentage' => '0.00',
                'discount_amount' => '0.00',
                'subtotal' => '14000000.00',
                'sort_order' => 0,
                'created_at' => '2026-02-12 15:08:24',
                'updated_at' => '2026-02-12 15:08:24',
            ],
            [
                'id' => 13,
                'invoice_id' => 3,
                'item_code' => 'ORD-7BB832',
                'item_name' => 'Solid Rak 4 Susun Knockdown',
                'description' => NULL,
                'quantity' => '1.00',
                'unit' => 'unit',
                'unit_price' => '3000000.00',
                'discount_percentage' => '0.00',
                'discount_amount' => '0.00',
                'subtotal' => '3000000.00',
                'sort_order' => 0,
                'created_at' => '2026-02-12 15:08:24',
                'updated_at' => '2026-02-12 15:08:24',
            ],
            [
                'id' => 14,
                'invoice_id' => 7,
                'item_code' => 'ORD-9B9EB7',
                'item_name' => 'Water Heater 30L',
                'description' => NULL,
                'quantity' => '1.00',
                'unit' => 'unit',
                'unit_price' => '4500000.00',
                'discount_percentage' => '0.00',
                'discount_amount' => '0.00',
                'subtotal' => '4500000.00',
                'sort_order' => 0,
                'created_at' => '2026-02-12 15:09:48',
                'updated_at' => '2026-02-12 15:09:48',
            ],
            [
                'id' => 15,
                'invoice_id' => 8,
                'item_code' => 'ORD-F6DFE1',
                'item_name' => 'Rak Tiris 4 Susun Knockdown',
                'description' => NULL,
                'quantity' => '1.00',
                'unit' => 'unit',
                'unit_price' => '3200000.00',
                'discount_percentage' => '0.00',
                'discount_amount' => '0.00',
                'subtotal' => '3200000.00',
                'sort_order' => 0,
                'created_at' => '2026-02-12 15:22:16',
                'updated_at' => '2026-02-12 15:22:16',
            ],
        ]);
    }
}
